### ISSUE TITLE
October 5th 2016 Deliverables

### ISSUE THREAD

**Issue by mlee156** [Upward-Spiral-Science/seelviz#18]
Link to presentation: https://neurodatadesign.github.io/seelviz/reveal/week_105.html

Big Picture: By the end of this week give Ailey a pipeline that is useful and easy to use/modify
Memorize that 1 voxel is 2 bytes

> Note: Edited by Albert below the hash-line to specify delegation of tasks for "Show the 40,000 brightest points in registered space relative to the registered region"

Tasks:

Jon:
- [x] Complete pipeline and make Python package.  Pipeline code should be [pip installable](https://pypi.python.org/pypi/clarityviz/0.0.1).
- [x] Provide evidence that the pipeline works.  Testing [here](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/ClarityVizPipelineResultsAccuracy.ipynb).
- [ ] Complete [documentation](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/ClarityViz%20Tutorial.ipynb) and organize Github repository 

Daniel: 
- [ ] Recheck Scree plots and eigenvalues to make sure they are accurate
- [ ] Extend x axis for the degree chart
- [ ] Clustering coefficient should not go above one - Make sure to re-plot so that the clustering coefficient does not exceed one 

Luke:
- [x] Create Docker for pipeline with Albert once pipeline is complete
  https://hub.docker.com/r/lkzhu1/ubuntu/ 
- [x] Show the 40,000 brightest points in registered space relative to the registered region with Albert, Tony

Tony:
- [x] Address Davi Bock's issue - make a plotly plot of Cocaine 174 where voxels are colored according to component size
- [Jupyter Notebook containing a generalized Plotly plotting script for density](https://neurodatadesign.github.io/seelviz/reveal/october5stuff/ChangingPlotlyColorByDensity.html).
  - Deliverable was to apply it to Cocaine174 using ball size of 25, to color the voxels according to component size.
    [Here](https://neurodatadesign.github.io/seelviz/reveal/html/graphmlhtmls/Cocaine174localeq.5000.graphml.html) is a 5000 point downsampled version I made initially (verified accuracy by finding max brightness values and comparing them to the node values on the chart).
    [Here](https://neurodatadesign.github.io/seelviz/reveal/html/graphmlhtmls/Cocaine174localeqbig.graphml.html) is the 40k node false color version I made.  I also checked the maximum brightness value and compared it to the brightness I got by scanning the list.  
  - For cross referencing, made a heat map coded for each 5%; shown [here](https://neurodatadesign.github.io/seelviz/reveal/html/graphmlhtmls/Cocaine174localeq.5000.graphmlheatmap.html) is the corresponding edge to color mapping for the downsampled Cocaine174.  [Here](https://neurodatadesign.github.io/seelviz/reveal/html/graphmlhtmls/Cocaine174localeqbig.graphmlheatmap.html) is the corresponding edge to color mapping for the full scale Cocaine174 plot.
- [x] Show the 40,000 brightest points in registered space relative to the registered region with Albert, Luke

Albert:
- [x] Create Docker for pipeline with Luke once pipeline is complete
  https://hub.docker.com/r/lkzhu1/ubuntu/ 
- [x] Show the 40,000 brightest points in registered space relative to the registered region with Luke, Tony
  Deliverable evidence listed below
- [x] Set up package page for prototype with installation instructions
  https://github.com/alee156/clviz
  Build passes on travis-ci
  https://travis-ci.org/alee156/clviz
###### 

"Show the 40,000 brightest points in registered space relative to the registered region with Luke, Albert, Tony" is a task for Luke, Albert, and Tony: The following is the splitting of tasks

Albert: 
- [x] Downsample or obtain atlas and one raw image so that they are less than 2 GB in size
  Learned from Kwame how to downsample effectively using "spacing".
  https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/miniatlas.nii
  https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Ndreg%20Simple%20Downsampling%20Method.ipynb
- [x] Write code for aligning atlas to the raw images instead of other way around
  https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/ReverseAlignmentDownsampled.ipynb
  https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/albert/brainalign.py
  https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/albert/reverse_affine_annotations.png
- [x] Write code used for resolution 5 images on server
  https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/albert/brainalign.py

Luke:
- [x] Run code on resolution 5 images using server
  https://github.com/NeuroDataDesign/seelviz/tree/gh-pages/albert
- [x] Create plotly plot representing each region of the brain as a different color
  https://neurodatadesign.github.io/seelviz/reveal/html/graphmlhtmls/Control258localeq.region_color.html
- [x] Sum intensity in each region
  https://neurodatadesign.github.io/seelviz/reveal/html/Control258localeq.region_activity.html
  https://neurodatadesign.github.io/seelviz/reveal/html/Control258localeq.region_activity_blackbg.html

Tony:
- [?] Create plotly plot of graphml network on new brain
  - [Jupyter notebook code for raw graphML to 3D plot with edges](https://neurodatadesign.github.io/seelviz/reveal/october5stuff/plotlygraphmlonly.html).
  - [Control258](https://neurodatadesign.github.io/seelviz/reveal/html/graphmlhtmls/Control258localeq.graphml.html) 40k nodes.
  - [Aut1374](https://neurodatadesign.github.io/seelviz/reveal/html/graphmlhtmls/Aut1374localeq.40000.100k.graphml.html) 100k nodes.
    - Need the new raw .nii files, this graphml was still captured from the old .nii
    - Data still not fully propogated for other channels for the new brains
- [x] Setup server and install all packages
  - Procured and setup a Google Cloud instance (similar to an Amazon AWS EC2 instance) free trial with $300 credits.
  - [CloudImage](../blob/gh-pages/reveal/october5stuff/googlecloudpng.png)
  - [SSH](../blob/gh-pages/reveal/october5stuff/sshgooglecloud.png)
  - [DockerImage](../blob/gh-pages/reveal/october5stuff/runningdockerpackages.png)

**Comment by mlee156** [comment]
@jovo @gkiar

**Comment by jovo** [comment]
@all - please make a detailed list of all the improvements/adjustments so we are all on the same page.

**Comment by mlee156** [comment]
@gkiar @jovo the issues have been updated!

**Comment by jovo** [comment]
i'm not quite sure what "Address Davi Bock's issue" means? how address? what issue?

" Clustering coefficient should not go above one"  true.  what will you do?

**Comment by mlee156** [comment]
@jovo @gkiar I updated the issues again!

**Comment by jovo** [comment]
better!

**Comment by gkiar** [comment]
@alee156 @toekneesunshine @lukezhu1 be more specific please - how many of the brightest points? What does "useable form" mean for downsampling the image? @jonl1096 does making the python package mean you will have it on pip? Such that I can clone and then run `python setup.py install`? What is your DoD here?

**Comment by mlee156** [comment]
@gkiar I updated the deliverables again!

**Comment by gkiar** [comment]
👌

**Comment by jonl1096** [comment]
<img width="698" alt="screen shot 2016-10-05 at 4 59 09 pm" src="https://cloud.githubusercontent.com/assets/10394145/19131365/21b37390-8b1d-11e6-87b9-87df6d7edf78.png">
