### ISSUE TITLE
Weekly Deliverables for 9/6/2016

### ISSUE THREAD

**Issue by mlee156** [Upward-Spiral-Science/seelviz#2]
@alee156
- [x] Create plotly graphs for 12 Clarity brains

https://upward-spiral-science.github.io/seelviz/clarityjs/Cocaine174localeq.html
https://upward-spiral-science.github.io/seelviz/clarityjs/Cocaine175localeq.html
https://upward-spiral-science.github.io/seelviz/clarityjs/Cocaine178localeq.html
https://upward-spiral-science.github.io/seelviz/clarityjs/Control181localeq.html
https://upward-spiral-science.github.io/seelviz/clarityjs/Control182localeq.html
https://upward-spiral-science.github.io/seelviz/clarityjs/Control189localeq.html
https://upward-spiral-science.github.io/seelviz/clarityjs/Control239localeq.html
https://upward-spiral-science.github.io/seelviz/clarityjs/Control258localeq.html
https://upward-spiral-science.github.io/seelviz/clarityjs/Fear187localeq.html
https://upward-spiral-science.github.io/seelviz/clarityjs/Fear197localeq.html
https://upward-spiral-science.github.io/seelviz/clarityjs/Fear199localeq.html
https://upward-spiral-science.github.io/seelviz/clarityjs/Fear200localeq.html

@Tony&Luke
- [x] Create 100,000 brightest points

https://upward-spiral-science.github.io/seelviz/csv/Fear199biglocaleq.brightest.csv
- [x] Connect nearest points graph 

https://github.com/Upward-Spiral-Science/seelviz/tree/gh-pages/graphfiles
- [x] Port into some viz media

https://github.com/Upward-Spiral-Science/seelviz/blob/gh-pages/graphfiles/Rplot.png

**Comment by mlee156** [comment]
https://upward-spiral-science.github.io/seelviz/reveal/week_906.html#/

**Comment by toekneesunshine** [comment]
Goals: 
Overlay atlas

**Comment by gkiar** [comment]
👌  @toekneesunshine please ensure that goal is transferred to the new issue.
