### ISSUE TITLE
Count the number of bright points in each region

### ISSUE THREAD

**Issue by mlee156** [Upward-Spiral-Science/seelviz#36]
- [x] Count the number of bright points in each region

**Comment by toekneesunshine** [comment]
This was a deliverable for 11/7.
If you look here: https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/Atlas%20Region%20Graph%20on%20Aut1367.ipynb

In the middle I've documented how to find the number of bright points in a labeled region.

CSV output here:

https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/Aut1367Counts.csv
