### ISSUE TITLE
Obtain image of the general brain region and report back to Jovo asap

### ISSUE THREAD

**Issue by mlee156** [Upward-Spiral-Science/seelviz#47]
Obtain image of the general brain region and report back to Jovo asap

**Comment by toekneesunshine** [comment]
I messaged Jovo over our group Slack channel, and I sent him a link to the region in question ([link here](http://atlas.brain-map.org/atlas?atlas=1#atlas=1&plate=100960224&structure=8&x=5279.928152901786&y=3738.435243879046&zoom=-3&resolution=11.97&z=6)).  

During the atlas registration step, each individual coordinate gets a tag which delineates its exact location "eg: red nucleus".  However, if the process has trouble finding a specific location, the atlas just says it's in the most general region aka "general cell bodies and regions".  We'll update our version of ndreg and report back if we're still getting this error.
