### ISSUE TITLE
Deliverables for February 6th

### ISSUE THREAD

**Issue by mlee156** [Upward-Spiral-Science/seelviz#63]
# Committed

|status |  deliverable | notes |
| :---|  :--- |  :--- |
|👍  | [ClearMap's "Spot Detection" algorithm analysis.](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/albert/clearmap-spotdetection.md), [docker](https://hub.docker.com/r/alee156/clearmap/)  | @alee156 |
| | Graph estimation and matching algorithm analysis. [Graph Matching algorithm notebook](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/Graph_Matching_algorithm.md.html)    | @lukezhu1  |
| 👍 | Create cell detection section in pipeline and implement discriminability if possible. [Connectivity notebook](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/algorithms/Connectivity%20.ipynb), [Connectivity Code](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/algorithms/connectivity.py), [# cells per region csv](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/algorithms/Fear199specific_counts.csv), [reworked pipeline code](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/algorithms/analysis.py), [New brain w/ regions](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/algorithms/Fear199_region.html) [Old Brain](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/algorithms/Aut1367_region_pointcloud.html)  | @jonl1096  |
| 👍  | [ClearMap's "Ilastik" algorithm analysis](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Tony/ipynb/ClearMap%20Ilastik%20Analysis.ipynb) -> if same as regular Ilastik then implementation. | @toekneesunshine  |

**Comment by jovo** [comment]
@jonl1096 if i understand correctly, you will show the results of your pipeline, which eats a CLARITY volume, and spits out:

1. \# of cells per region
2. adjacency matrix of connectivity between regions.

even better, a visualization of both!

other guys:
each of you will present something following this: 
https://github.com/neurodata/checklists/blob/master/methods_paper.md

skipping the sections i skipped in the demo here:
https://github.com/neurodata/checklists/blob/master/Tutorials/MATLAB/algs_example/methods_paper_example.md
