### ISSUE TITLE
Deliverables for Feb 27

### ISSUE THREAD

**Issue by jonl1096** [Upward-Spiral-Science/seelviz#66]
# Committed

Note: Deliverable for Thursday for everyone is to help create a document describing the process of converting our nifti images into tensor images fit for processing with Ailey's pipeline. Note everyone's contribution to said document must be clear. @gkiar 

Deliverables for Monday will be created after discussing with Greg about our findings about tensor image creation.

|status |  deliverable | notes |
| :---|  :--- |  :--- |
| 👍 |  [Work on visualizing FA tensor structs.](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/Tony/ipynb/FA%20Visualizations%20Final.ipynb) | @alee156|
| 👍 |  [Work on visualizing FA tensor structs.](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/Tony/ipynb/FA%20Visualizations%20Final.ipynb) | @lukezhu1  |
| 👍 |  [Work on visualizing FA tensor structs.](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/Tony/ipynb/FA%20Visualizations%20Final.ipynb) | @jonl1096  |
| 👍 |  [Work on visualizing FA tensor structs.](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/Tony/ipynb/FA%20Visualizations%20Final.ipynb) | @toekneesunshine  |

**Comment by gkiar** [comment]
@alee156 @lukezhu1 @jonl1096 @toekneesunshine:
  - Ideally, creating the tensor image should be straightforward given the paper. What I would like to see on Monday from this group is:
    - a methods.md explaining and implementing and visualizing the process of turning your image into a tensor image. Tensors can be visualized as FA maps, which are color-coded by direction and strengthened by intensity. Very google-able. I have code for this in the [gh:neurodata/ndmg](https://github.com/neurodata/ndmg) repo.
    - a markdown explaining the exact tractography (and parameters if possible) used in the paper sent by Ailey, and a list of other methods such as Dipy which are similar (i.e. if they did deterministic tracing, don't yet list or worry about probabilistic tracing)

**Comment by toekneesunshine** [comment]
A [link](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/Tony/ipynb/Generating%20Structure%20Tensors.ipynb) to our Thursday deliverable!  It includes a discussion of generating the structure tensors, what we've attempted so far, and stuff we'd like to go over for office hours on Thursday.

This document will be further updated for our Monday deliverables.
