### ISSUE TITLE
Deliverables for March 6th

### ISSUE THREAD

**Issue by mlee156** [Upward-Spiral-Science/seelviz#67]
@alee156 and @lukezhu1 
- [X] [DoD is a new figure of both the current tensors, and the tensors which you produce when using downsampled data which covers a larger region of the brain.](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Albert_Jupyter/Final%2BNotebook.ipynb)

(https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Albert_Jupyter/Final%2BDownsampled2.ipynb)

https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Albert_Jupyter/Final%2BDownsampled%20(1).ipynb

https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Albert_Jupyter/Final%2BDownsampled.ipynb

@toekneesunshine and @jonl1096 
- [X] [Port over Ailey's code to Python](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/Tony/ipynb/GeneratingaStructuralTensor.ipynb)
- [X] [Deliverable is thorough testing and outputs of both Matlab and new Python code](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/Tony/ipynb/Structure%20Tensor%20Testing%20Final.ipynb)
- [Even more testing (this time with norm data)](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/Tony/ipynb/Structure%20Tensor%20Testing%20Final%20(With%20Other%20Data).ipynb)

---------

Thursday Deliverables
@alee156 @lukezhu1 
- [X] have a downsampled brain (show me it)
https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/downsampled.nii
https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/AlbertImages/March2017/downsample.png?raw=true
- [X] write pseudocode for the algorithm I've described regarding plotting tensor maps, which can be gleaned from reading the code linked.
https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/AlbertImages/March2017/pseudocode.png?raw=true

@toekneesunshine @jonl1096
- [X] [pseudocode for computing structure tensors](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/algorithms/pseudocode.png)

**Comment by gkiar** [comment]
@alee156 @lukezhu1: too vague, I updated below. Also, what's for Thursday ("clear progress" is ambiguous)?
  - [ ] DoD is a new figure of both the current tensors, and the tensors which you produce when using downsampled data which covers a larger region of the brain.

An example of how we turn tensors into FA values and plot them is [here](https://github.com/neurodata/ndmg/blob/master/ndmg/stats/qa_tensor.py#L37).

@toekneesunshine @jonl1096: also too vague, updated below. Also, what's for Thursday ("clear progress" is ambiguous)?
- [ ] Python implementation of tensor calculation from CLARITY brains. DoD is simulation data run through the provided MATLAB code for tensor generation, and through the Python code, showing the same results.

**Comment by mlee156** [comment]
@gkiar For me and luke we'll downsample some of the data into cubes that make sense, and bring you a report about the specific approach we're planning to take

**Comment by gkiar** [comment]
@alee156 what do "cubes that make sense" mean? & what do you mean "approach you plan to take"? Please plot the tensors in the way that I've described, in which you are using RGB to highlight direction. If you look at the code I linked, it plots a 3x3 grid of these maps, you should simply plot 1 of those on your data for now.

For Thursday how about you do:
- [ ] have a downsampled brain (show me it)
- [ ] write pseudocode for the algorithm I've described regarding plotting tensor maps, which can be gleaned from reading the code linked.

**Comment by mlee156** [comment]
sounds good

**Comment by toekneesunshine** [comment]
@gkiar 

- [X] For Thursday, Jon and I will have pseudocode tracing each step that the CAPTURE pipeline MATLAB script/associated scripts uses.
